---
environment: "production"
cluster_name: "liveclipper_cluster"

region: "eu-west-3"
ami: "ami-04a4acda26ca36de0"

ssh_key_options:
  generate_auto: true # auto-generate ssh keys and keeps them in state file
  jumpbox_key_path: ""
  worker_key_path: ""
  manager_key_path: ""

jumpbox:
  name: "jumpbox"
  instance_type: "t2.micro"
  cloud: "aws"

managers:
  - name: "manager10"
    instance_type: "t2.micro"
    cloud: "aws"
    user: "ubuntu"
  
  # - name: "manager1"
  #   instance_type: "t2.micro"
  #   cloud: "aws"
  
  - name: "manager2"
    instance_type: "t2.micro"
    cloud: "aws"
    user: "ubuntu"
  
  - name: "manager3"
    instance_type: "s-1vcpu-1gb"
    cloud: "do"
    region: "nyc2"
    image: "ubuntu-20-04-x64"
    user: "root"
  
  - name: "manager5"
    instance_type: "s-1vcpu-1gb"
    cloud: "do"
    region: "nyc2"
    image: "ubuntu-20-04-x64"
    user: "root"
  
  - name: "manager11"
    instance_type: "g6-nanode-1"
    cloud: "linode"
    region: "us-east"
    user: "root"
    image: "linode/ubuntu22.04"
  
  - name: "manager12"
    instance_type: "g6-nanode-1"
    cloud: "linode"
    region: "us-east"
    user: "root"
    image: "linode/ubuntu22.04"

  

workers:    
  - name: "worker0"
    instance_type: "t2.micro"
    cloud: "aws"
    user: "ubuntu"
  
  - name: "worker1"
    instance_type: "s-1vcpu-1gb"
    cloud: "do"
    region: "nyc2"
    image: "ubuntu-20-04-x64"
    user: "root"
  
  - name: "worker2"
    instance_type: "s-1vcpu-1gb"
    cloud: "do"
    region: "nyc2"
    image: "ubuntu-20-04-x64"
    user: "root"
  
  - name: "worker12"
    instance_type: "g6-nanode-1"
    cloud: "linode"
    region: "us-east"
    user: "root"
    image: "linode/ubuntu22.04"

  # - name: "worker2"
  #   instance_type: "t2.micro"
  #   cloud: "aws"
  
  # - name: "worker3"
  #   instance_type: "t2.micro"
  #   cloud: "do"


security:
  jumpbox:
    egress:
      - from_port: 0
        to_port: 0
        protocol: "-1"
        cidr_blocks:
          - "0.0.0.0/0"
    ingress:
      - from_port: 22
        to_port: 22
        protocol: "tcp"
        cidr_blocks:
          - "92.239.148.217/32"  #tayyabs public ip, only allow ssh from this ip
  manager:
    ingress:
      - from_port: 22
        to_port: 22
        protocol: "tcp"
        cidr_blocks:
          - "jumpbox.ip"
          - "92.239.148.217/32"  #tayyabs public ip, only allow ssh from this ip
      
      - from_port: 2377
        to_port: 2377
        protocol: "tcp"
        cidr_blocks:
          - "worker.ip"
          - "manager.ip"
      
      - from_port: 7946
        to_port: 7946
        protocol: "tcp"
        cidr_blocks:
          - "worker.ip"
          - "manager.ip"
      
      - from_port: 7946
        to_port: 7946
        protocol: "udp"
        cidr_blocks:
          - "worker.ip"
          - "manager.ip"

    egress:
      - from_port: 0
        to_port: 0
        protocol: "-1"
        cidr_blocks:
          - "0.0.0.0/0"

  worker:
    ingress:
      - from_port: 22
        to_port: 22
        protocol: "tcp"
        cidr_blocks:
          - "jumpbox.ip"
      
      - from_port: 7946
        to_port: 7946
        protocol: "tcp"
        cidr_blocks:
          - "manager.ip"
      - from_port: 7946
        to_port: 7946
        protocol: "udp"
        cidr_blocks:
          - "manager.ip"
    egress:
      - from_port: 0
        to_port: 0
        protocol: "-1"
        cidr_blocks:
          - "0.0.0.0/0"