---
- name: Setup
  hosts: jumpbox
  become: true
  gather_facts: true
  roles:
    - common


- name: Setup
  hosts: manager
  become: true
  gather_facts: true
  roles:
    - common


- name: Setup
  hosts: worker
  become: true
  gather_facts: true
  roles:
    - common